name: Sync Rabbit-Spec Config

on:
  schedule:
    - cron: '0 0 * * *'  # 每天定时同步一次
  workflow_dispatch: # 也可手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: 'Rabbit-Spec/Surge'
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: 'main'

      - name: Commit changes
        run: |
          git config --local user.email "your-email@example.com"
          git config --local user.name "yourusername"
          git add -A
          git commit -m "Auto-sync with Rabbit-Spec"
          git push
